/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as NasilCalisirRouteImport } from './routes/nasil-calisir'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as KullanimKosullariRouteImport } from './routes/kullanim-kosullari'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as GuvenlikRouteImport } from './routes/guvenlik'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as CerezPolitikasiRouteImport } from './routes/cerez-politikasi'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UyeIdRouteImport } from './routes/uye.$id'
import { Route as IlanIdRouteImport } from './routes/ilan.$id'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated.profil'
import { Route as AuthenticatedIlanlarimRouteImport } from './routes/_authenticated.ilanlarim'
import { Route as AuthenticatedIlanVerRouteImport } from './routes/_authenticated.ilan-ver'
import { Route as AuthenticatedDestekRouteImport } from './routes/_authenticated.destek'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedMesajlarIndexRouteImport } from './routes/_authenticated.mesajlar.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedMesajlarIdRouteImport } from './routes/_authenticated.mesajlar.$id'
import { Route as AuthenticatedAdminYorumlarRouteImport } from './routes/_authenticated.admin.yorumlar'
import { Route as AuthenticatedAdminYayinRouteImport } from './routes/_authenticated.admin.yayin'
import { Route as AuthenticatedAdminTicketlarRouteImport } from './routes/_authenticated.admin.ticketlar'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated.admin.seo'
import { Route as AuthenticatedAdminRozetlerRouteImport } from './routes/_authenticated.admin.rozetler'
import { Route as AuthenticatedAdminRaporlarRouteImport } from './routes/_authenticated.admin.raporlar'
import { Route as AuthenticatedAdminLoglarRouteImport } from './routes/_authenticated.admin.loglar'
import { Route as AuthenticatedAdminKullanicilarRouteImport } from './routes/_authenticated.admin.kullanicilar'
import { Route as AuthenticatedAdminIlanlarRouteImport } from './routes/_authenticated.admin.ilanlar'
import { Route as AuthenticatedAdminDuyurularRouteImport } from './routes/_authenticated.admin.duyurular'
import { Route as AuthenticatedAdminBildirimlerRouteImport } from './routes/_authenticated.admin.bildirimler'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NasilCalisirRoute = NasilCalisirRouteImport.update({
  id: '/nasil-calisir',
  path: '/nasil-calisir',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const KullanimKosullariRoute = KullanimKosullariRouteImport.update({
  id: '/kullanim-kosullari',
  path: '/kullanim-kosullari',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const GuvenlikRoute = GuvenlikRouteImport.update({
  id: '/guvenlik',
  path: '/guvenlik',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const CerezPolitikasiRoute = CerezPolitikasiRouteImport.update({
  id: '/cerez-politikasi',
  path: '/cerez-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UyeIdRoute = UyeIdRouteImport.update({
  id: '/uye/$id',
  path: '/uye/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanIdRoute = IlanIdRouteImport.update({
  id: '/ilan/$id',
  path: '/ilan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIlanlarimRoute = AuthenticatedIlanlarimRouteImport.update({
  id: '/ilanlarim',
  path: '/ilanlarim',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIlanVerRoute = AuthenticatedIlanVerRouteImport.update({
  id: '/ilan-ver',
  path: '/ilan-ver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDestekRoute = AuthenticatedDestekRouteImport.update({
  id: '/destek',
  path: '/destek',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMesajlarIndexRoute =
  AuthenticatedMesajlarIndexRouteImport.update({
    id: '/mesajlar/',
    path: '/mesajlar/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedMesajlarIdRoute = AuthenticatedMesajlarIdRouteImport.update({
  id: '/mesajlar/$id',
  path: '/mesajlar/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminYorumlarRoute =
  AuthenticatedAdminYorumlarRouteImport.update({
    id: '/yorumlar',
    path: '/yorumlar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminYayinRoute = AuthenticatedAdminYayinRouteImport.update({
  id: '/yayin',
  path: '/yayin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTicketlarRoute =
  AuthenticatedAdminTicketlarRouteImport.update({
    id: '/ticketlar',
    path: '/ticketlar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRozetlerRoute =
  AuthenticatedAdminRozetlerRouteImport.update({
    id: '/rozetler',
    path: '/rozetler',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRaporlarRoute =
  AuthenticatedAdminRaporlarRouteImport.update({
    id: '/raporlar',
    path: '/raporlar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLoglarRoute =
  AuthenticatedAdminLoglarRouteImport.update({
    id: '/loglar',
    path: '/loglar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKullanicilarRoute =
  AuthenticatedAdminKullanicilarRouteImport.update({
    id: '/kullanicilar',
    path: '/kullanicilar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIlanlarRoute =
  AuthenticatedAdminIlanlarRouteImport.update({
    id: '/ilanlar',
    path: '/ilanlar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDuyurularRoute =
  AuthenticatedAdminDuyurularRouteImport.update({
    id: '/duyurular',
    path: '/duyurular',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBildirimlerRoute =
  AuthenticatedAdminBildirimlerRouteImport.update({
    id: '/bildirimler',
    path: '/bildirimler',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/gizlilik': typeof GizlilikRoute
  '/guvenlik': typeof GuvenlikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kullanim-kosullari': typeof KullanimKosullariRoute
  '/kvkk': typeof KvkkRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/destek': typeof AuthenticatedDestekRoute
  '/ilan-ver': typeof AuthenticatedIlanVerRoute
  '/ilanlarim': typeof AuthenticatedIlanlarimRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/ilan/$id': typeof IlanIdRoute
  '/uye/$id': typeof UyeIdRoute
  '/admin/bildirimler': typeof AuthenticatedAdminBildirimlerRoute
  '/admin/duyurular': typeof AuthenticatedAdminDuyurularRoute
  '/admin/ilanlar': typeof AuthenticatedAdminIlanlarRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/loglar': typeof AuthenticatedAdminLoglarRoute
  '/admin/raporlar': typeof AuthenticatedAdminRaporlarRoute
  '/admin/rozetler': typeof AuthenticatedAdminRozetlerRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/ticketlar': typeof AuthenticatedAdminTicketlarRoute
  '/admin/yayin': typeof AuthenticatedAdminYayinRoute
  '/admin/yorumlar': typeof AuthenticatedAdminYorumlarRoute
  '/mesajlar/$id': typeof AuthenticatedMesajlarIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/mesajlar/': typeof AuthenticatedMesajlarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/gizlilik': typeof GizlilikRoute
  '/guvenlik': typeof GuvenlikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kullanim-kosullari': typeof KullanimKosullariRoute
  '/kvkk': typeof KvkkRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/destek': typeof AuthenticatedDestekRoute
  '/ilan-ver': typeof AuthenticatedIlanVerRoute
  '/ilanlarim': typeof AuthenticatedIlanlarimRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/ilan/$id': typeof IlanIdRoute
  '/uye/$id': typeof UyeIdRoute
  '/admin/bildirimler': typeof AuthenticatedAdminBildirimlerRoute
  '/admin/duyurular': typeof AuthenticatedAdminDuyurularRoute
  '/admin/ilanlar': typeof AuthenticatedAdminIlanlarRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/loglar': typeof AuthenticatedAdminLoglarRoute
  '/admin/raporlar': typeof AuthenticatedAdminRaporlarRoute
  '/admin/rozetler': typeof AuthenticatedAdminRozetlerRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/ticketlar': typeof AuthenticatedAdminTicketlarRoute
  '/admin/yayin': typeof AuthenticatedAdminYayinRoute
  '/admin/yorumlar': typeof AuthenticatedAdminYorumlarRoute
  '/mesajlar/$id': typeof AuthenticatedMesajlarIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/mesajlar': typeof AuthenticatedMesajlarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/gizlilik': typeof GizlilikRoute
  '/guvenlik': typeof GuvenlikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kullanim-kosullari': typeof KullanimKosullariRoute
  '/kvkk': typeof KvkkRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/destek': typeof AuthenticatedDestekRoute
  '/_authenticated/ilan-ver': typeof AuthenticatedIlanVerRoute
  '/_authenticated/ilanlarim': typeof AuthenticatedIlanlarimRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/ilan/$id': typeof IlanIdRoute
  '/uye/$id': typeof UyeIdRoute
  '/_authenticated/admin/bildirimler': typeof AuthenticatedAdminBildirimlerRoute
  '/_authenticated/admin/duyurular': typeof AuthenticatedAdminDuyurularRoute
  '/_authenticated/admin/ilanlar': typeof AuthenticatedAdminIlanlarRoute
  '/_authenticated/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/_authenticated/admin/loglar': typeof AuthenticatedAdminLoglarRoute
  '/_authenticated/admin/raporlar': typeof AuthenticatedAdminRaporlarRoute
  '/_authenticated/admin/rozetler': typeof AuthenticatedAdminRozetlerRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/ticketlar': typeof AuthenticatedAdminTicketlarRoute
  '/_authenticated/admin/yayin': typeof AuthenticatedAdminYayinRoute
  '/_authenticated/admin/yorumlar': typeof AuthenticatedAdminYorumlarRoute
  '/_authenticated/mesajlar/$id': typeof AuthenticatedMesajlarIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/mesajlar/': typeof AuthenticatedMesajlarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads.txt'
    | '/auth'
    | '/cerez-politikasi'
    | '/gizlilik'
    | '/guvenlik'
    | '/hakkimizda'
    | '/iletisim'
    | '/kullanim-kosullari'
    | '/kvkk'
    | '/nasil-calisir'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/destek'
    | '/ilan-ver'
    | '/ilanlarim'
    | '/profil'
    | '/ilan/$id'
    | '/uye/$id'
    | '/admin/bildirimler'
    | '/admin/duyurular'
    | '/admin/ilanlar'
    | '/admin/kullanicilar'
    | '/admin/loglar'
    | '/admin/raporlar'
    | '/admin/rozetler'
    | '/admin/seo'
    | '/admin/ticketlar'
    | '/admin/yayin'
    | '/admin/yorumlar'
    | '/mesajlar/$id'
    | '/admin/'
    | '/mesajlar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads.txt'
    | '/auth'
    | '/cerez-politikasi'
    | '/gizlilik'
    | '/guvenlik'
    | '/hakkimizda'
    | '/iletisim'
    | '/kullanim-kosullari'
    | '/kvkk'
    | '/nasil-calisir'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/destek'
    | '/ilan-ver'
    | '/ilanlarim'
    | '/profil'
    | '/ilan/$id'
    | '/uye/$id'
    | '/admin/bildirimler'
    | '/admin/duyurular'
    | '/admin/ilanlar'
    | '/admin/kullanicilar'
    | '/admin/loglar'
    | '/admin/raporlar'
    | '/admin/rozetler'
    | '/admin/seo'
    | '/admin/ticketlar'
    | '/admin/yayin'
    | '/admin/yorumlar'
    | '/mesajlar/$id'
    | '/admin'
    | '/mesajlar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ads.txt'
    | '/auth'
    | '/cerez-politikasi'
    | '/gizlilik'
    | '/guvenlik'
    | '/hakkimizda'
    | '/iletisim'
    | '/kullanim-kosullari'
    | '/kvkk'
    | '/nasil-calisir'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/destek'
    | '/_authenticated/ilan-ver'
    | '/_authenticated/ilanlarim'
    | '/_authenticated/profil'
    | '/ilan/$id'
    | '/uye/$id'
    | '/_authenticated/admin/bildirimler'
    | '/_authenticated/admin/duyurular'
    | '/_authenticated/admin/ilanlar'
    | '/_authenticated/admin/kullanicilar'
    | '/_authenticated/admin/loglar'
    | '/_authenticated/admin/raporlar'
    | '/_authenticated/admin/rozetler'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/ticketlar'
    | '/_authenticated/admin/yayin'
    | '/_authenticated/admin/yorumlar'
    | '/_authenticated/mesajlar/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/mesajlar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdsDottxtRoute: typeof AdsDottxtRoute
  AuthRoute: typeof AuthRoute
  CerezPolitikasiRoute: typeof CerezPolitikasiRoute
  GizlilikRoute: typeof GizlilikRoute
  GuvenlikRoute: typeof GuvenlikRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  KullanimKosullariRoute: typeof KullanimKosullariRoute
  KvkkRoute: typeof KvkkRoute
  NasilCalisirRoute: typeof NasilCalisirRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IlanIdRoute: typeof IlanIdRoute
  UyeIdRoute: typeof UyeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasil-calisir': {
      id: '/nasil-calisir'
      path: '/nasil-calisir'
      fullPath: '/nasil-calisir'
      preLoaderRoute: typeof NasilCalisirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kullanim-kosullari': {
      id: '/kullanim-kosullari'
      path: '/kullanim-kosullari'
      fullPath: '/kullanim-kosullari'
      preLoaderRoute: typeof KullanimKosullariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guvenlik': {
      id: '/guvenlik'
      path: '/guvenlik'
      fullPath: '/guvenlik'
      preLoaderRoute: typeof GuvenlikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerez-politikasi': {
      id: '/cerez-politikasi'
      path: '/cerez-politikasi'
      fullPath: '/cerez-politikasi'
      preLoaderRoute: typeof CerezPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uye/$id': {
      id: '/uye/$id'
      path: '/uye/$id'
      fullPath: '/uye/$id'
      preLoaderRoute: typeof UyeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan/$id': {
      id: '/ilan/$id'
      path: '/ilan/$id'
      fullPath: '/ilan/$id'
      preLoaderRoute: typeof IlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ilanlarim': {
      id: '/_authenticated/ilanlarim'
      path: '/ilanlarim'
      fullPath: '/ilanlarim'
      preLoaderRoute: typeof AuthenticatedIlanlarimRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ilan-ver': {
      id: '/_authenticated/ilan-ver'
      path: '/ilan-ver'
      fullPath: '/ilan-ver'
      preLoaderRoute: typeof AuthenticatedIlanVerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/destek': {
      id: '/_authenticated/destek'
      path: '/destek'
      fullPath: '/destek'
      preLoaderRoute: typeof AuthenticatedDestekRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mesajlar/': {
      id: '/_authenticated/mesajlar/'
      path: '/mesajlar'
      fullPath: '/mesajlar/'
      preLoaderRoute: typeof AuthenticatedMesajlarIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/mesajlar/$id': {
      id: '/_authenticated/mesajlar/$id'
      path: '/mesajlar/$id'
      fullPath: '/mesajlar/$id'
      preLoaderRoute: typeof AuthenticatedMesajlarIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/yorumlar': {
      id: '/_authenticated/admin/yorumlar'
      path: '/yorumlar'
      fullPath: '/admin/yorumlar'
      preLoaderRoute: typeof AuthenticatedAdminYorumlarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/yayin': {
      id: '/_authenticated/admin/yayin'
      path: '/yayin'
      fullPath: '/admin/yayin'
      preLoaderRoute: typeof AuthenticatedAdminYayinRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ticketlar': {
      id: '/_authenticated/admin/ticketlar'
      path: '/ticketlar'
      fullPath: '/admin/ticketlar'
      preLoaderRoute: typeof AuthenticatedAdminTicketlarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rozetler': {
      id: '/_authenticated/admin/rozetler'
      path: '/rozetler'
      fullPath: '/admin/rozetler'
      preLoaderRoute: typeof AuthenticatedAdminRozetlerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/raporlar': {
      id: '/_authenticated/admin/raporlar'
      path: '/raporlar'
      fullPath: '/admin/raporlar'
      preLoaderRoute: typeof AuthenticatedAdminRaporlarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/loglar': {
      id: '/_authenticated/admin/loglar'
      path: '/loglar'
      fullPath: '/admin/loglar'
      preLoaderRoute: typeof AuthenticatedAdminLoglarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kullanicilar': {
      id: '/_authenticated/admin/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/admin/kullanicilar'
      preLoaderRoute: typeof AuthenticatedAdminKullanicilarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ilanlar': {
      id: '/_authenticated/admin/ilanlar'
      path: '/ilanlar'
      fullPath: '/admin/ilanlar'
      preLoaderRoute: typeof AuthenticatedAdminIlanlarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/duyurular': {
      id: '/_authenticated/admin/duyurular'
      path: '/duyurular'
      fullPath: '/admin/duyurular'
      preLoaderRoute: typeof AuthenticatedAdminDuyurularRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bildirimler': {
      id: '/_authenticated/admin/bildirimler'
      path: '/bildirimler'
      fullPath: '/admin/bildirimler'
      preLoaderRoute: typeof AuthenticatedAdminBildirimlerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBildirimlerRoute: typeof AuthenticatedAdminBildirimlerRoute
  AuthenticatedAdminDuyurularRoute: typeof AuthenticatedAdminDuyurularRoute
  AuthenticatedAdminIlanlarRoute: typeof AuthenticatedAdminIlanlarRoute
  AuthenticatedAdminKullanicilarRoute: typeof AuthenticatedAdminKullanicilarRoute
  AuthenticatedAdminLoglarRoute: typeof AuthenticatedAdminLoglarRoute
  AuthenticatedAdminRaporlarRoute: typeof AuthenticatedAdminRaporlarRoute
  AuthenticatedAdminRozetlerRoute: typeof AuthenticatedAdminRozetlerRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminTicketlarRoute: typeof AuthenticatedAdminTicketlarRoute
  AuthenticatedAdminYayinRoute: typeof AuthenticatedAdminYayinRoute
  AuthenticatedAdminYorumlarRoute: typeof AuthenticatedAdminYorumlarRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBildirimlerRoute: AuthenticatedAdminBildirimlerRoute,
  AuthenticatedAdminDuyurularRoute: AuthenticatedAdminDuyurularRoute,
  AuthenticatedAdminIlanlarRoute: AuthenticatedAdminIlanlarRoute,
  AuthenticatedAdminKullanicilarRoute: AuthenticatedAdminKullanicilarRoute,
  AuthenticatedAdminLoglarRoute: AuthenticatedAdminLoglarRoute,
  AuthenticatedAdminRaporlarRoute: AuthenticatedAdminRaporlarRoute,
  AuthenticatedAdminRozetlerRoute: AuthenticatedAdminRozetlerRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminTicketlarRoute: AuthenticatedAdminTicketlarRoute,
  AuthenticatedAdminYayinRoute: AuthenticatedAdminYayinRoute,
  AuthenticatedAdminYorumlarRoute: AuthenticatedAdminYorumlarRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDestekRoute: typeof AuthenticatedDestekRoute
  AuthenticatedIlanVerRoute: typeof AuthenticatedIlanVerRoute
  AuthenticatedIlanlarimRoute: typeof AuthenticatedIlanlarimRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedMesajlarIdRoute: typeof AuthenticatedMesajlarIdRoute
  AuthenticatedMesajlarIndexRoute: typeof AuthenticatedMesajlarIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDestekRoute: AuthenticatedDestekRoute,
  AuthenticatedIlanVerRoute: AuthenticatedIlanVerRoute,
  AuthenticatedIlanlarimRoute: AuthenticatedIlanlarimRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedMesajlarIdRoute: AuthenticatedMesajlarIdRoute,
  AuthenticatedMesajlarIndexRoute: AuthenticatedMesajlarIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdsDottxtRoute: AdsDottxtRoute,
  AuthRoute: AuthRoute,
  CerezPolitikasiRoute: CerezPolitikasiRoute,
  GizlilikRoute: GizlilikRoute,
  GuvenlikRoute: GuvenlikRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  KullanimKosullariRoute: KullanimKosullariRoute,
  KvkkRoute: KvkkRoute,
  NasilCalisirRoute: NasilCalisirRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IlanIdRoute: IlanIdRoute,
  UyeIdRoute: UyeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
