/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NasilCalisirRouteImport } from './routes/nasil-calisir'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as KullanimKosullariRouteImport } from './routes/kullanim-kosullari'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as GuvenlikRouteImport } from './routes/guvenlik'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as CerezPolitikasiRouteImport } from './routes/cerez-politikasi'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IstanbulIndexRouteImport } from './routes/istanbul.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UyeIdRouteImport } from './routes/uye.$id'
import { Route as RehberEvcilHayvanBakimiFiyatlariRouteImport } from './routes/rehber.evcil-hayvan-bakimi-fiyatlari'
import { Route as IstanbulIlceRouteImport } from './routes/istanbul.$ilce'
import { Route as IlanIdRouteImport } from './routes/ilan.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedPromosyonlarimRouteImport } from './routes/_authenticated.promosyonlarim'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated.profil'
import { Route as AuthenticatedIlanlarimRouteImport } from './routes/_authenticated.ilanlarim'
import { Route as AuthenticatedIlanVerRouteImport } from './routes/_authenticated.ilan-ver'
import { Route as AuthenticatedDestekRouteImport } from './routes/_authenticated.destek'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedMesajlarIndexRouteImport } from './routes/_authenticated.mesajlar.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedMesajlarIdRouteImport } from './routes/_authenticated.mesajlar.$id'
import { Route as AuthenticatedAdminYorumlarRouteImport } from './routes/_authenticated.admin.yorumlar'
import { Route as AuthenticatedAdminYayinRouteImport } from './routes/_authenticated.admin.yayin'
import { Route as AuthenticatedAdminVeriRouteImport } from './routes/_authenticated.admin.veri'
import { Route as AuthenticatedAdminTicketlarRouteImport } from './routes/_authenticated.admin.ticketlar'
import { Route as AuthenticatedAdminSmtpRouteImport } from './routes/_authenticated.admin.smtp'
import { Route as AuthenticatedAdminShopierRouteImport } from './routes/_authenticated.admin.shopier'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated.admin.seo'
import { Route as AuthenticatedAdminRozetlerRouteImport } from './routes/_authenticated.admin.rozetler'
import { Route as AuthenticatedAdminReklamlarRouteImport } from './routes/_authenticated.admin.reklamlar'
import { Route as AuthenticatedAdminRaporlarRouteImport } from './routes/_authenticated.admin.raporlar'
import { Route as AuthenticatedAdminPaketlerRouteImport } from './routes/_authenticated.admin.paketler'
import { Route as AuthenticatedAdminOdemelerRouteImport } from './routes/_authenticated.admin.odemeler'
import { Route as AuthenticatedAdminMesajlarRouteImport } from './routes/_authenticated.admin.mesajlar'
import { Route as AuthenticatedAdminLoglarRouteImport } from './routes/_authenticated.admin.loglar'
import { Route as AuthenticatedAdminKullanicilarRouteImport } from './routes/_authenticated.admin.kullanicilar'
import { Route as AuthenticatedAdminKategorilerRouteImport } from './routes/_authenticated.admin.kategoriler'
import { Route as AuthenticatedAdminIlanlarRouteImport } from './routes/_authenticated.admin.ilanlar'
import { Route as AuthenticatedAdminHavaleRouteImport } from './routes/_authenticated.admin.havale'
import { Route as AuthenticatedAdminDuyurularRouteImport } from './routes/_authenticated.admin.duyurular'
import { Route as AuthenticatedAdminDosyalarRouteImport } from './routes/_authenticated.admin.dosyalar'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated.admin.blog'
import { Route as AuthenticatedAdminBildirimlerRouteImport } from './routes/_authenticated.admin.bildirimler'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NasilCalisirRoute = NasilCalisirRouteImport.update({
  id: '/nasil-calisir',
  path: '/nasil-calisir',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const KullanimKosullariRoute = KullanimKosullariRouteImport.update({
  id: '/kullanim-kosullari',
  path: '/kullanim-kosullari',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const GuvenlikRoute = GuvenlikRouteImport.update({
  id: '/guvenlik',
  path: '/guvenlik',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const CerezPolitikasiRoute = CerezPolitikasiRouteImport.update({
  id: '/cerez-politikasi',
  path: '/cerez-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IstanbulIndexRoute = IstanbulIndexRouteImport.update({
  id: '/istanbul/',
  path: '/istanbul/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const UyeIdRoute = UyeIdRouteImport.update({
  id: '/uye/$id',
  path: '/uye/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RehberEvcilHayvanBakimiFiyatlariRoute =
  RehberEvcilHayvanBakimiFiyatlariRouteImport.update({
    id: '/rehber/evcil-hayvan-bakimi-fiyatlari',
    path: '/rehber/evcil-hayvan-bakimi-fiyatlari',
    getParentRoute: () => rootRouteImport,
  } as any)
const IstanbulIlceRoute = IstanbulIlceRouteImport.update({
  id: '/istanbul/$ilce',
  path: '/istanbul/$ilce',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanIdRoute = IlanIdRouteImport.update({
  id: '/ilan/$id',
  path: '/ilan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedPromosyonlarimRoute =
  AuthenticatedPromosyonlarimRouteImport.update({
    id: '/promosyonlarim',
    path: '/promosyonlarim',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIlanlarimRoute = AuthenticatedIlanlarimRouteImport.update({
  id: '/ilanlarim',
  path: '/ilanlarim',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIlanVerRoute = AuthenticatedIlanVerRouteImport.update({
  id: '/ilan-ver',
  path: '/ilan-ver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDestekRoute = AuthenticatedDestekRouteImport.update({
  id: '/destek',
  path: '/destek',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMesajlarIndexRoute =
  AuthenticatedMesajlarIndexRouteImport.update({
    id: '/mesajlar/',
    path: '/mesajlar/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedMesajlarIdRoute = AuthenticatedMesajlarIdRouteImport.update({
  id: '/mesajlar/$id',
  path: '/mesajlar/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminYorumlarRoute =
  AuthenticatedAdminYorumlarRouteImport.update({
    id: '/yorumlar',
    path: '/yorumlar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminYayinRoute = AuthenticatedAdminYayinRouteImport.update({
  id: '/yayin',
  path: '/yayin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVeriRoute = AuthenticatedAdminVeriRouteImport.update({
  id: '/veri',
  path: '/veri',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTicketlarRoute =
  AuthenticatedAdminTicketlarRouteImport.update({
    id: '/ticketlar',
    path: '/ticketlar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSmtpRoute = AuthenticatedAdminSmtpRouteImport.update({
  id: '/smtp',
  path: '/smtp',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminShopierRoute =
  AuthenticatedAdminShopierRouteImport.update({
    id: '/shopier',
    path: '/shopier',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRozetlerRoute =
  AuthenticatedAdminRozetlerRouteImport.update({
    id: '/rozetler',
    path: '/rozetler',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReklamlarRoute =
  AuthenticatedAdminReklamlarRouteImport.update({
    id: '/reklamlar',
    path: '/reklamlar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRaporlarRoute =
  AuthenticatedAdminRaporlarRouteImport.update({
    id: '/raporlar',
    path: '/raporlar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaketlerRoute =
  AuthenticatedAdminPaketlerRouteImport.update({
    id: '/paketler',
    path: '/paketler',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOdemelerRoute =
  AuthenticatedAdminOdemelerRouteImport.update({
    id: '/odemeler',
    path: '/odemeler',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMesajlarRoute =
  AuthenticatedAdminMesajlarRouteImport.update({
    id: '/mesajlar',
    path: '/mesajlar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLoglarRoute =
  AuthenticatedAdminLoglarRouteImport.update({
    id: '/loglar',
    path: '/loglar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKullanicilarRoute =
  AuthenticatedAdminKullanicilarRouteImport.update({
    id: '/kullanicilar',
    path: '/kullanicilar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKategorilerRoute =
  AuthenticatedAdminKategorilerRouteImport.update({
    id: '/kategoriler',
    path: '/kategoriler',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIlanlarRoute =
  AuthenticatedAdminIlanlarRouteImport.update({
    id: '/ilanlar',
    path: '/ilanlar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHavaleRoute =
  AuthenticatedAdminHavaleRouteImport.update({
    id: '/havale',
    path: '/havale',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDuyurularRoute =
  AuthenticatedAdminDuyurularRouteImport.update({
    id: '/duyurular',
    path: '/duyurular',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDosyalarRoute =
  AuthenticatedAdminDosyalarRouteImport.update({
    id: '/dosyalar',
    path: '/dosyalar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBildirimlerRoute =
  AuthenticatedAdminBildirimlerRouteImport.update({
    id: '/bildirimler',
    path: '/bildirimler',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/gizlilik': typeof GizlilikRoute
  '/guvenlik': typeof GuvenlikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kullanim-kosullari': typeof KullanimKosullariRoute
  '/kvkk': typeof KvkkRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/destek': typeof AuthenticatedDestekRoute
  '/ilan-ver': typeof AuthenticatedIlanVerRoute
  '/ilanlarim': typeof AuthenticatedIlanlarimRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/promosyonlarim': typeof AuthenticatedPromosyonlarimRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ilan/$id': typeof IlanIdRoute
  '/istanbul/$ilce': typeof IstanbulIlceRoute
  '/rehber/evcil-hayvan-bakimi-fiyatlari': typeof RehberEvcilHayvanBakimiFiyatlariRoute
  '/uye/$id': typeof UyeIdRoute
  '/blog/': typeof BlogIndexRoute
  '/istanbul/': typeof IstanbulIndexRoute
  '/admin/bildirimler': typeof AuthenticatedAdminBildirimlerRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/dosyalar': typeof AuthenticatedAdminDosyalarRoute
  '/admin/duyurular': typeof AuthenticatedAdminDuyurularRoute
  '/admin/havale': typeof AuthenticatedAdminHavaleRoute
  '/admin/ilanlar': typeof AuthenticatedAdminIlanlarRoute
  '/admin/kategoriler': typeof AuthenticatedAdminKategorilerRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/loglar': typeof AuthenticatedAdminLoglarRoute
  '/admin/mesajlar': typeof AuthenticatedAdminMesajlarRoute
  '/admin/odemeler': typeof AuthenticatedAdminOdemelerRoute
  '/admin/paketler': typeof AuthenticatedAdminPaketlerRoute
  '/admin/raporlar': typeof AuthenticatedAdminRaporlarRoute
  '/admin/reklamlar': typeof AuthenticatedAdminReklamlarRoute
  '/admin/rozetler': typeof AuthenticatedAdminRozetlerRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/shopier': typeof AuthenticatedAdminShopierRoute
  '/admin/smtp': typeof AuthenticatedAdminSmtpRoute
  '/admin/ticketlar': typeof AuthenticatedAdminTicketlarRoute
  '/admin/veri': typeof AuthenticatedAdminVeriRoute
  '/admin/yayin': typeof AuthenticatedAdminYayinRoute
  '/admin/yorumlar': typeof AuthenticatedAdminYorumlarRoute
  '/mesajlar/$id': typeof AuthenticatedMesajlarIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/mesajlar/': typeof AuthenticatedMesajlarIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/gizlilik': typeof GizlilikRoute
  '/guvenlik': typeof GuvenlikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kullanim-kosullari': typeof KullanimKosullariRoute
  '/kvkk': typeof KvkkRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/destek': typeof AuthenticatedDestekRoute
  '/ilan-ver': typeof AuthenticatedIlanVerRoute
  '/ilanlarim': typeof AuthenticatedIlanlarimRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/promosyonlarim': typeof AuthenticatedPromosyonlarimRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ilan/$id': typeof IlanIdRoute
  '/istanbul/$ilce': typeof IstanbulIlceRoute
  '/rehber/evcil-hayvan-bakimi-fiyatlari': typeof RehberEvcilHayvanBakimiFiyatlariRoute
  '/uye/$id': typeof UyeIdRoute
  '/blog': typeof BlogIndexRoute
  '/istanbul': typeof IstanbulIndexRoute
  '/admin/bildirimler': typeof AuthenticatedAdminBildirimlerRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/dosyalar': typeof AuthenticatedAdminDosyalarRoute
  '/admin/duyurular': typeof AuthenticatedAdminDuyurularRoute
  '/admin/havale': typeof AuthenticatedAdminHavaleRoute
  '/admin/ilanlar': typeof AuthenticatedAdminIlanlarRoute
  '/admin/kategoriler': typeof AuthenticatedAdminKategorilerRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/loglar': typeof AuthenticatedAdminLoglarRoute
  '/admin/mesajlar': typeof AuthenticatedAdminMesajlarRoute
  '/admin/odemeler': typeof AuthenticatedAdminOdemelerRoute
  '/admin/paketler': typeof AuthenticatedAdminPaketlerRoute
  '/admin/raporlar': typeof AuthenticatedAdminRaporlarRoute
  '/admin/reklamlar': typeof AuthenticatedAdminReklamlarRoute
  '/admin/rozetler': typeof AuthenticatedAdminRozetlerRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/shopier': typeof AuthenticatedAdminShopierRoute
  '/admin/smtp': typeof AuthenticatedAdminSmtpRoute
  '/admin/ticketlar': typeof AuthenticatedAdminTicketlarRoute
  '/admin/veri': typeof AuthenticatedAdminVeriRoute
  '/admin/yayin': typeof AuthenticatedAdminYayinRoute
  '/admin/yorumlar': typeof AuthenticatedAdminYorumlarRoute
  '/mesajlar/$id': typeof AuthenticatedMesajlarIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/mesajlar': typeof AuthenticatedMesajlarIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/gizlilik': typeof GizlilikRoute
  '/guvenlik': typeof GuvenlikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kullanim-kosullari': typeof KullanimKosullariRoute
  '/kvkk': typeof KvkkRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/destek': typeof AuthenticatedDestekRoute
  '/_authenticated/ilan-ver': typeof AuthenticatedIlanVerRoute
  '/_authenticated/ilanlarim': typeof AuthenticatedIlanlarimRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/promosyonlarim': typeof AuthenticatedPromosyonlarimRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ilan/$id': typeof IlanIdRoute
  '/istanbul/$ilce': typeof IstanbulIlceRoute
  '/rehber/evcil-hayvan-bakimi-fiyatlari': typeof RehberEvcilHayvanBakimiFiyatlariRoute
  '/uye/$id': typeof UyeIdRoute
  '/blog/': typeof BlogIndexRoute
  '/istanbul/': typeof IstanbulIndexRoute
  '/_authenticated/admin/bildirimler': typeof AuthenticatedAdminBildirimlerRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/dosyalar': typeof AuthenticatedAdminDosyalarRoute
  '/_authenticated/admin/duyurular': typeof AuthenticatedAdminDuyurularRoute
  '/_authenticated/admin/havale': typeof AuthenticatedAdminHavaleRoute
  '/_authenticated/admin/ilanlar': typeof AuthenticatedAdminIlanlarRoute
  '/_authenticated/admin/kategoriler': typeof AuthenticatedAdminKategorilerRoute
  '/_authenticated/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/_authenticated/admin/loglar': typeof AuthenticatedAdminLoglarRoute
  '/_authenticated/admin/mesajlar': typeof AuthenticatedAdminMesajlarRoute
  '/_authenticated/admin/odemeler': typeof AuthenticatedAdminOdemelerRoute
  '/_authenticated/admin/paketler': typeof AuthenticatedAdminPaketlerRoute
  '/_authenticated/admin/raporlar': typeof AuthenticatedAdminRaporlarRoute
  '/_authenticated/admin/reklamlar': typeof AuthenticatedAdminReklamlarRoute
  '/_authenticated/admin/rozetler': typeof AuthenticatedAdminRozetlerRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/shopier': typeof AuthenticatedAdminShopierRoute
  '/_authenticated/admin/smtp': typeof AuthenticatedAdminSmtpRoute
  '/_authenticated/admin/ticketlar': typeof AuthenticatedAdminTicketlarRoute
  '/_authenticated/admin/veri': typeof AuthenticatedAdminVeriRoute
  '/_authenticated/admin/yayin': typeof AuthenticatedAdminYayinRoute
  '/_authenticated/admin/yorumlar': typeof AuthenticatedAdminYorumlarRoute
  '/_authenticated/mesajlar/$id': typeof AuthenticatedMesajlarIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/mesajlar/': typeof AuthenticatedMesajlarIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads.txt'
    | '/auth'
    | '/blog'
    | '/cerez-politikasi'
    | '/gizlilik'
    | '/guvenlik'
    | '/hakkimizda'
    | '/iletisim'
    | '/kullanim-kosullari'
    | '/kvkk'
    | '/nasil-calisir'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/destek'
    | '/ilan-ver'
    | '/ilanlarim'
    | '/profil'
    | '/promosyonlarim'
    | '/blog/$slug'
    | '/ilan/$id'
    | '/istanbul/$ilce'
    | '/rehber/evcil-hayvan-bakimi-fiyatlari'
    | '/uye/$id'
    | '/blog/'
    | '/istanbul/'
    | '/admin/bildirimler'
    | '/admin/blog'
    | '/admin/dosyalar'
    | '/admin/duyurular'
    | '/admin/havale'
    | '/admin/ilanlar'
    | '/admin/kategoriler'
    | '/admin/kullanicilar'
    | '/admin/loglar'
    | '/admin/mesajlar'
    | '/admin/odemeler'
    | '/admin/paketler'
    | '/admin/raporlar'
    | '/admin/reklamlar'
    | '/admin/rozetler'
    | '/admin/seo'
    | '/admin/shopier'
    | '/admin/smtp'
    | '/admin/ticketlar'
    | '/admin/veri'
    | '/admin/yayin'
    | '/admin/yorumlar'
    | '/mesajlar/$id'
    | '/admin/'
    | '/mesajlar/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads.txt'
    | '/auth'
    | '/cerez-politikasi'
    | '/gizlilik'
    | '/guvenlik'
    | '/hakkimizda'
    | '/iletisim'
    | '/kullanim-kosullari'
    | '/kvkk'
    | '/nasil-calisir'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/destek'
    | '/ilan-ver'
    | '/ilanlarim'
    | '/profil'
    | '/promosyonlarim'
    | '/blog/$slug'
    | '/ilan/$id'
    | '/istanbul/$ilce'
    | '/rehber/evcil-hayvan-bakimi-fiyatlari'
    | '/uye/$id'
    | '/blog'
    | '/istanbul'
    | '/admin/bildirimler'
    | '/admin/blog'
    | '/admin/dosyalar'
    | '/admin/duyurular'
    | '/admin/havale'
    | '/admin/ilanlar'
    | '/admin/kategoriler'
    | '/admin/kullanicilar'
    | '/admin/loglar'
    | '/admin/mesajlar'
    | '/admin/odemeler'
    | '/admin/paketler'
    | '/admin/raporlar'
    | '/admin/reklamlar'
    | '/admin/rozetler'
    | '/admin/seo'
    | '/admin/shopier'
    | '/admin/smtp'
    | '/admin/ticketlar'
    | '/admin/veri'
    | '/admin/yayin'
    | '/admin/yorumlar'
    | '/mesajlar/$id'
    | '/admin'
    | '/mesajlar'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ads.txt'
    | '/auth'
    | '/blog'
    | '/cerez-politikasi'
    | '/gizlilik'
    | '/guvenlik'
    | '/hakkimizda'
    | '/iletisim'
    | '/kullanim-kosullari'
    | '/kvkk'
    | '/nasil-calisir'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/destek'
    | '/_authenticated/ilan-ver'
    | '/_authenticated/ilanlarim'
    | '/_authenticated/profil'
    | '/_authenticated/promosyonlarim'
    | '/blog/$slug'
    | '/ilan/$id'
    | '/istanbul/$ilce'
    | '/rehber/evcil-hayvan-bakimi-fiyatlari'
    | '/uye/$id'
    | '/blog/'
    | '/istanbul/'
    | '/_authenticated/admin/bildirimler'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/dosyalar'
    | '/_authenticated/admin/duyurular'
    | '/_authenticated/admin/havale'
    | '/_authenticated/admin/ilanlar'
    | '/_authenticated/admin/kategoriler'
    | '/_authenticated/admin/kullanicilar'
    | '/_authenticated/admin/loglar'
    | '/_authenticated/admin/mesajlar'
    | '/_authenticated/admin/odemeler'
    | '/_authenticated/admin/paketler'
    | '/_authenticated/admin/raporlar'
    | '/_authenticated/admin/reklamlar'
    | '/_authenticated/admin/rozetler'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/shopier'
    | '/_authenticated/admin/smtp'
    | '/_authenticated/admin/ticketlar'
    | '/_authenticated/admin/veri'
    | '/_authenticated/admin/yayin'
    | '/_authenticated/admin/yorumlar'
    | '/_authenticated/mesajlar/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/mesajlar/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdsDottxtRoute: typeof AdsDottxtRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CerezPolitikasiRoute: typeof CerezPolitikasiRoute
  GizlilikRoute: typeof GizlilikRoute
  GuvenlikRoute: typeof GuvenlikRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  KullanimKosullariRoute: typeof KullanimKosullariRoute
  KvkkRoute: typeof KvkkRoute
  NasilCalisirRoute: typeof NasilCalisirRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IlanIdRoute: typeof IlanIdRoute
  IstanbulIlceRoute: typeof IstanbulIlceRoute
  RehberEvcilHayvanBakimiFiyatlariRoute: typeof RehberEvcilHayvanBakimiFiyatlariRoute
  UyeIdRoute: typeof UyeIdRoute
  IstanbulIndexRoute: typeof IstanbulIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasil-calisir': {
      id: '/nasil-calisir'
      path: '/nasil-calisir'
      fullPath: '/nasil-calisir'
      preLoaderRoute: typeof NasilCalisirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kullanim-kosullari': {
      id: '/kullanim-kosullari'
      path: '/kullanim-kosullari'
      fullPath: '/kullanim-kosullari'
      preLoaderRoute: typeof KullanimKosullariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guvenlik': {
      id: '/guvenlik'
      path: '/guvenlik'
      fullPath: '/guvenlik'
      preLoaderRoute: typeof GuvenlikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerez-politikasi': {
      id: '/cerez-politikasi'
      path: '/cerez-politikasi'
      fullPath: '/cerez-politikasi'
      preLoaderRoute: typeof CerezPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/istanbul/': {
      id: '/istanbul/'
      path: '/istanbul'
      fullPath: '/istanbul/'
      preLoaderRoute: typeof IstanbulIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/uye/$id': {
      id: '/uye/$id'
      path: '/uye/$id'
      fullPath: '/uye/$id'
      preLoaderRoute: typeof UyeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rehber/evcil-hayvan-bakimi-fiyatlari': {
      id: '/rehber/evcil-hayvan-bakimi-fiyatlari'
      path: '/rehber/evcil-hayvan-bakimi-fiyatlari'
      fullPath: '/rehber/evcil-hayvan-bakimi-fiyatlari'
      preLoaderRoute: typeof RehberEvcilHayvanBakimiFiyatlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/istanbul/$ilce': {
      id: '/istanbul/$ilce'
      path: '/istanbul/$ilce'
      fullPath: '/istanbul/$ilce'
      preLoaderRoute: typeof IstanbulIlceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan/$id': {
      id: '/ilan/$id'
      path: '/ilan/$id'
      fullPath: '/ilan/$id'
      preLoaderRoute: typeof IlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/promosyonlarim': {
      id: '/_authenticated/promosyonlarim'
      path: '/promosyonlarim'
      fullPath: '/promosyonlarim'
      preLoaderRoute: typeof AuthenticatedPromosyonlarimRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ilanlarim': {
      id: '/_authenticated/ilanlarim'
      path: '/ilanlarim'
      fullPath: '/ilanlarim'
      preLoaderRoute: typeof AuthenticatedIlanlarimRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ilan-ver': {
      id: '/_authenticated/ilan-ver'
      path: '/ilan-ver'
      fullPath: '/ilan-ver'
      preLoaderRoute: typeof AuthenticatedIlanVerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/destek': {
      id: '/_authenticated/destek'
      path: '/destek'
      fullPath: '/destek'
      preLoaderRoute: typeof AuthenticatedDestekRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mesajlar/': {
      id: '/_authenticated/mesajlar/'
      path: '/mesajlar'
      fullPath: '/mesajlar/'
      preLoaderRoute: typeof AuthenticatedMesajlarIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/mesajlar/$id': {
      id: '/_authenticated/mesajlar/$id'
      path: '/mesajlar/$id'
      fullPath: '/mesajlar/$id'
      preLoaderRoute: typeof AuthenticatedMesajlarIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/yorumlar': {
      id: '/_authenticated/admin/yorumlar'
      path: '/yorumlar'
      fullPath: '/admin/yorumlar'
      preLoaderRoute: typeof AuthenticatedAdminYorumlarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/yayin': {
      id: '/_authenticated/admin/yayin'
      path: '/yayin'
      fullPath: '/admin/yayin'
      preLoaderRoute: typeof AuthenticatedAdminYayinRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/veri': {
      id: '/_authenticated/admin/veri'
      path: '/veri'
      fullPath: '/admin/veri'
      preLoaderRoute: typeof AuthenticatedAdminVeriRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ticketlar': {
      id: '/_authenticated/admin/ticketlar'
      path: '/ticketlar'
      fullPath: '/admin/ticketlar'
      preLoaderRoute: typeof AuthenticatedAdminTicketlarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/smtp': {
      id: '/_authenticated/admin/smtp'
      path: '/smtp'
      fullPath: '/admin/smtp'
      preLoaderRoute: typeof AuthenticatedAdminSmtpRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shopier': {
      id: '/_authenticated/admin/shopier'
      path: '/shopier'
      fullPath: '/admin/shopier'
      preLoaderRoute: typeof AuthenticatedAdminShopierRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rozetler': {
      id: '/_authenticated/admin/rozetler'
      path: '/rozetler'
      fullPath: '/admin/rozetler'
      preLoaderRoute: typeof AuthenticatedAdminRozetlerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reklamlar': {
      id: '/_authenticated/admin/reklamlar'
      path: '/reklamlar'
      fullPath: '/admin/reklamlar'
      preLoaderRoute: typeof AuthenticatedAdminReklamlarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/raporlar': {
      id: '/_authenticated/admin/raporlar'
      path: '/raporlar'
      fullPath: '/admin/raporlar'
      preLoaderRoute: typeof AuthenticatedAdminRaporlarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/paketler': {
      id: '/_authenticated/admin/paketler'
      path: '/paketler'
      fullPath: '/admin/paketler'
      preLoaderRoute: typeof AuthenticatedAdminPaketlerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/odemeler': {
      id: '/_authenticated/admin/odemeler'
      path: '/odemeler'
      fullPath: '/admin/odemeler'
      preLoaderRoute: typeof AuthenticatedAdminOdemelerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mesajlar': {
      id: '/_authenticated/admin/mesajlar'
      path: '/mesajlar'
      fullPath: '/admin/mesajlar'
      preLoaderRoute: typeof AuthenticatedAdminMesajlarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/loglar': {
      id: '/_authenticated/admin/loglar'
      path: '/loglar'
      fullPath: '/admin/loglar'
      preLoaderRoute: typeof AuthenticatedAdminLoglarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kullanicilar': {
      id: '/_authenticated/admin/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/admin/kullanicilar'
      preLoaderRoute: typeof AuthenticatedAdminKullanicilarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kategoriler': {
      id: '/_authenticated/admin/kategoriler'
      path: '/kategoriler'
      fullPath: '/admin/kategoriler'
      preLoaderRoute: typeof AuthenticatedAdminKategorilerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ilanlar': {
      id: '/_authenticated/admin/ilanlar'
      path: '/ilanlar'
      fullPath: '/admin/ilanlar'
      preLoaderRoute: typeof AuthenticatedAdminIlanlarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/havale': {
      id: '/_authenticated/admin/havale'
      path: '/havale'
      fullPath: '/admin/havale'
      preLoaderRoute: typeof AuthenticatedAdminHavaleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/duyurular': {
      id: '/_authenticated/admin/duyurular'
      path: '/duyurular'
      fullPath: '/admin/duyurular'
      preLoaderRoute: typeof AuthenticatedAdminDuyurularRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dosyalar': {
      id: '/_authenticated/admin/dosyalar'
      path: '/dosyalar'
      fullPath: '/admin/dosyalar'
      preLoaderRoute: typeof AuthenticatedAdminDosyalarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bildirimler': {
      id: '/_authenticated/admin/bildirimler'
      path: '/bildirimler'
      fullPath: '/admin/bildirimler'
      preLoaderRoute: typeof AuthenticatedAdminBildirimlerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBildirimlerRoute: typeof AuthenticatedAdminBildirimlerRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminDosyalarRoute: typeof AuthenticatedAdminDosyalarRoute
  AuthenticatedAdminDuyurularRoute: typeof AuthenticatedAdminDuyurularRoute
  AuthenticatedAdminHavaleRoute: typeof AuthenticatedAdminHavaleRoute
  AuthenticatedAdminIlanlarRoute: typeof AuthenticatedAdminIlanlarRoute
  AuthenticatedAdminKategorilerRoute: typeof AuthenticatedAdminKategorilerRoute
  AuthenticatedAdminKullanicilarRoute: typeof AuthenticatedAdminKullanicilarRoute
  AuthenticatedAdminLoglarRoute: typeof AuthenticatedAdminLoglarRoute
  AuthenticatedAdminMesajlarRoute: typeof AuthenticatedAdminMesajlarRoute
  AuthenticatedAdminOdemelerRoute: typeof AuthenticatedAdminOdemelerRoute
  AuthenticatedAdminPaketlerRoute: typeof AuthenticatedAdminPaketlerRoute
  AuthenticatedAdminRaporlarRoute: typeof AuthenticatedAdminRaporlarRoute
  AuthenticatedAdminReklamlarRoute: typeof AuthenticatedAdminReklamlarRoute
  AuthenticatedAdminRozetlerRoute: typeof AuthenticatedAdminRozetlerRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminShopierRoute: typeof AuthenticatedAdminShopierRoute
  AuthenticatedAdminSmtpRoute: typeof AuthenticatedAdminSmtpRoute
  AuthenticatedAdminTicketlarRoute: typeof AuthenticatedAdminTicketlarRoute
  AuthenticatedAdminVeriRoute: typeof AuthenticatedAdminVeriRoute
  AuthenticatedAdminYayinRoute: typeof AuthenticatedAdminYayinRoute
  AuthenticatedAdminYorumlarRoute: typeof AuthenticatedAdminYorumlarRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBildirimlerRoute: AuthenticatedAdminBildirimlerRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminDosyalarRoute: AuthenticatedAdminDosyalarRoute,
  AuthenticatedAdminDuyurularRoute: AuthenticatedAdminDuyurularRoute,
  AuthenticatedAdminHavaleRoute: AuthenticatedAdminHavaleRoute,
  AuthenticatedAdminIlanlarRoute: AuthenticatedAdminIlanlarRoute,
  AuthenticatedAdminKategorilerRoute: AuthenticatedAdminKategorilerRoute,
  AuthenticatedAdminKullanicilarRoute: AuthenticatedAdminKullanicilarRoute,
  AuthenticatedAdminLoglarRoute: AuthenticatedAdminLoglarRoute,
  AuthenticatedAdminMesajlarRoute: AuthenticatedAdminMesajlarRoute,
  AuthenticatedAdminOdemelerRoute: AuthenticatedAdminOdemelerRoute,
  AuthenticatedAdminPaketlerRoute: AuthenticatedAdminPaketlerRoute,
  AuthenticatedAdminRaporlarRoute: AuthenticatedAdminRaporlarRoute,
  AuthenticatedAdminReklamlarRoute: AuthenticatedAdminReklamlarRoute,
  AuthenticatedAdminRozetlerRoute: AuthenticatedAdminRozetlerRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminShopierRoute: AuthenticatedAdminShopierRoute,
  AuthenticatedAdminSmtpRoute: AuthenticatedAdminSmtpRoute,
  AuthenticatedAdminTicketlarRoute: AuthenticatedAdminTicketlarRoute,
  AuthenticatedAdminVeriRoute: AuthenticatedAdminVeriRoute,
  AuthenticatedAdminYayinRoute: AuthenticatedAdminYayinRoute,
  AuthenticatedAdminYorumlarRoute: AuthenticatedAdminYorumlarRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDestekRoute: typeof AuthenticatedDestekRoute
  AuthenticatedIlanVerRoute: typeof AuthenticatedIlanVerRoute
  AuthenticatedIlanlarimRoute: typeof AuthenticatedIlanlarimRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedPromosyonlarimRoute: typeof AuthenticatedPromosyonlarimRoute
  AuthenticatedMesajlarIdRoute: typeof AuthenticatedMesajlarIdRoute
  AuthenticatedMesajlarIndexRoute: typeof AuthenticatedMesajlarIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDestekRoute: AuthenticatedDestekRoute,
  AuthenticatedIlanVerRoute: AuthenticatedIlanVerRoute,
  AuthenticatedIlanlarimRoute: AuthenticatedIlanlarimRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedPromosyonlarimRoute: AuthenticatedPromosyonlarimRoute,
  AuthenticatedMesajlarIdRoute: AuthenticatedMesajlarIdRoute,
  AuthenticatedMesajlarIndexRoute: AuthenticatedMesajlarIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdsDottxtRoute: AdsDottxtRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CerezPolitikasiRoute: CerezPolitikasiRoute,
  GizlilikRoute: GizlilikRoute,
  GuvenlikRoute: GuvenlikRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  KullanimKosullariRoute: KullanimKosullariRoute,
  KvkkRoute: KvkkRoute,
  NasilCalisirRoute: NasilCalisirRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IlanIdRoute: IlanIdRoute,
  IstanbulIlceRoute: IstanbulIlceRoute,
  RehberEvcilHayvanBakimiFiyatlariRoute: RehberEvcilHayvanBakimiFiyatlariRoute,
  UyeIdRoute: UyeIdRoute,
  IstanbulIndexRoute: IstanbulIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
